spring:
  application:
    name: AppMicro
  config:
    import: "optional:configserver:http://localhost:8889"
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration